# Generated by Django 4.1.7 on 2023-03-10 13:27

from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0002_rename_name_artist_artist_name_song'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FileField(upload_to='score_path')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_v1.song')),
            ],
        ),
    ]
