# Generated by Django 4.1.7 on 2023-03-11 07:08

from django.db import migrations
from django.db import models

import api_v1.models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0003_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'verbose_name': 'Ноты', 'verbose_name_plural': 'Ноты'},
        ),
        migrations.AddField(
            model_name='score',
            name='score_type',
            field=models.CharField(choices=[('GP', 'GuitarPro file'), ('PDF', 'Adobe Reader file'), ('JPG', 'JPG picture')], default='PDF', max_length=3),
        ),
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.FileField(upload_to=api_v1.models.score_path),
        ),
    ]
