# Generated by Django 4.2.4 on 2023-08-27 22:21

from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0005_song_performer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='performer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='performer_song_set', to='api_v1.artist'),
        ),
    ]
