name: Django Test

on:
  push:
    branches: 
      - "main"
      - "dev"
    tags:
      - "v*.*.*"
  pull_request:
    branches: 
      - "main"
      - "dev"

jobs:
  django-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.0

    - name: Set up Python 
      id: setup-python
      uses: actions/setup-python@v4.7.0
      with:
        python-version-file: 'backend/.python-version'
    
    - name: Restore pip dependencies
      uses: actions/cache@v3
      id: cache-venv-dependencies
      with: 
        path: |
          venv
        key: ${{ runner.os }}-venv-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/backend/requirements.txt') }}

    - name: Install dependencies
      # if: steps.cache-venv-dependencies.outputs.cache-hit != 'true'
      run: |
        python -m venv venv
        . venv/bin/activate
        pip install --upgrade pip pip-tools flake8-django flake8
        pip-sync ./backend/requirements.txt

    - name: Run Tests
      env:
        DRUMSCORE_DEBUG: ${{ vars.DRUMSCORE_DEBUG }}
        DRUMSCORE_SECRET_KEY: ${{ secrets.DRUMSCORE_SECRET_KEY }}
        DRUMSCORE_ALLOWED_HOSTS: ${{ vars.DRUMSCORE_ALLOWED_HOSTS }}
        DRUMSCORE_LANGUAGE_CODE: ${{ vars.DRUMSCORE_LANGUAGE_CODE }}
        DRUMSCORE_TIME_ZONE: ${{ vars.DRUMSCORE_TIME_ZONE }}
        DRUMSCORE_DATABASE_URL: ${{ vars.DRUMSCORE_DATABASE_URL }}
        DRUMSCORE_SQLITE_URL: ${{ vars.DRUMSCORE_SQLITE_URL }}
        DRUMSCORE_SUPERUSER_USERNAME: ${{ secrets.DRUMSCORE_SUPERUSER_USERNAME }}
        DRUMSCORE_SUPERUSER_EMAIL: ${{ secrets.DRUMSCORE_SUPERUSER_EMAIL }}
        DRUMSCORE_SUPERUSER_PASSWORD: ${{ secrets.DRUMSCORE_SUPERUSER_PASSWORD }}
        
      run: |
        . venv/bin/activate
        cd backend
        python manage.py collectstatic --noinput
        python manage.py migrate --noinput
        python manage.py ensure_adminuser --no-input
        python manage.py test

    - name: Run the linter
      run: |
        . venv/bin/activate
        cd backend
        flake8 .

        